name: Build PsychoPy Studio 

on:
  # manual
  workflow_dispatch:  
    inputs:
      branch:
        description: 'PsychoPy Studio branch to build'
        required: true
        type: choice
        options:
          - dev
          - release
      dogfood:
        description: 'Building a dogfood intaller to test?'
        required: true
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  build:
    name: Build PsychoPy Studio
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: |
          npm i
      
      - name: Calculate dogfood version number
        id: dogfood
        run: |
          if [ $(git tag -l) ]; then
            dogfood = echo git rev-list $(git describe --tags --abbrev=0)..HEAD --count --branches ${{ github.event.inputs.branch }} --tags *
          else
            dogfood = git rev-list HEAD --count --branches ${{ github.event.inputs.branch }}
          fi
          echo "version=$(npm pkg get "version"| tr -d '"')${{ github.event.inputs.branch }}$(dogfood)" >> $GITHUB_OUTPUT
      
      - name: Modify version
        if: ${{ github.event.inputs.dogfood }}
        run: |
          npm pkg set "version"="${{ steps.dogfood.outputs.version }}"
          echo npm pkg get "version"
      
      - name: Build installer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          npm run build
      
      - name: Upload installers as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ runner.os }}_installer"
          path: 'out/PsychoPy_Studio_*.*'
          retention-days: 30





